{{- if .Values.kubedoor.master.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedoor-config
  namespace: kubedoor
data:
  CK_HOST: {{ .Values.clickhouse.CK_HOST | quote }}
  CK_PORT: {{ .Values.clickhouse.CK_PORT | quote }}
  CK_HTTP_PORT: {{ .Values.clickhouse.CK_HTTP_PORT | quote }}
  CK_USER: {{ .Values.clickhouse.CK_USER | quote }}
  CK_PASSWORD: {{ .Values.clickhouse.CK_PASSWORD | quote }}
  CK_DATABASE: kubedoor
  PROM_TYPE: {{ .Values.tsdb.type | quote }}
  {{- if eq .Values.tsdb.type "KubeDoor" }}
  PROM_URL: "http://{{ .Values.tsdb.vm_single.user }}:{{ .Values.tsdb.vm_single.passwd }}@victoria-metrics.kubedoor:8428"
  {{- else if eq .Values.tsdb.type "Victoria-Metrics-Cluster" }}
  PROM_URL: {{ .Values.tsdb.remoteRead | quote }}
  {{- else }}
  PROM_URL: {{ .Values.tsdb.url | quote }}
  {{- end }}
  PROM_K8S_TAG_KEY: {{ .Values.tsdb.external_labels_key | quote }}
  MSG_TYPE: {{ .Values.config.MSG_TYPE | quote }}
  MSG_TOKEN: {{ .Values.config.MSG_TOKEN | quote }}
  DEFAULT_AT: {{ .Values.kubedoor_alarm.DEFAULT_AT | quote }}
  ALERTMANAGER_EXTURL: {{ .Values.kubedoor_alarm.ALERTMANAGER_EXTURL | quote }}
  LOG_LEVEL: INFO
  ALERT_DEDUP_WINDOW: '300'
  DB_HOST: {{ .Values.mysql.DB_HOST | quote }}
  DB_NAME: {{ .Values.mysql.DB_NAME | quote }}
  DB_PASSWORD: {{ .Values.mysql.DB_PASSWORD | quote }}
  DB_PORT: {{ .Values.mysql.DB_PORT | quote }}
  DB_USER: {{ .Values.mysql.DB_USER | quote }}

  REGISTRY_SECRET: |
    {
      "swr.cn-south-1.myhuaweicloud.com": {
        "default": {
          "ak": "xxxxxxxx",
          "sk": "xxxxxxxxxxxxxxxxxxx"
        }
      },
      "registry.cn-shenzhen.aliyuncs.com": {
        "default": {
          "ak": "xxxxxxxxx",
          "sk": "xxxxxxxxxxxxxxxxxxx"
        },
        "myk8s-1": {
          "ak": "xxxxxxxxx",
          "sk": "xxxxxxxxxxxxxxxxxxx"
        }
      },
      "harbor.xxxxx.com": {
        "default": {
          "ak": "username",
          "sk": "password"
        }
      }
    }
  UPDATE_IMAGE: |
    {
      "default": {
        "isOperationAllowed": false
      },
      "k8s_name": {
        "isOperationAllowed": true,
        "allowedOperationPeriod": "19:00-08:00",
        "user": [
          "a0001",
          "a0002"
        ]
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedoor-master-file-cfg
  namespace: kubedoor
data:
  alert_rules.json: |
    {
      "global_ignore_rules": [
        {
          "name": "环境过滤规则(排除非生产环境[注意:当前未开启])",
          "enabled": false,
          "conditions": {
            "k8s": {
              "not_contains": ["prod"]
            }
          }
        },
        {
          "name": "常见忽略事件[示例:防止告警规则中有正常事件被匹配到,可以加到忽略规则中]",
          "enabled": true,
          "conditions": {
            "reason": {
              "contains": ["BackOffStart", "SuccessfulCreate", "SuccessfulMountVolume"]
            }
          }
        }
      ],
      "alert_rules": [
        {
          "name": "关键事件告警",
          "enabled": true,
          "severity": "critical",
          "conditions": {
            "reason": {
              "contains": ["OOM", "NodeNotReady", "Unreachable"]
            },
            "level": {
              "contains": ["Warning"]
            }
          }
        },
        {
          "name": "健康检查失败告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "reason": {
              "contains": ["Unhealthy"]
            },
            "name": {
              "not_starts_with": ["deploy-datax-cloud-"]
            },
            "count": {
              "greater_than": 1
            }
          }
        },
        {
          "name": "重启事件告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "message": {
              "contains": ["restart"]
            }
          }
        },
        {
          "name": "挂载失败告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "reason": {
              "contains": ["FailedMount", "FailedAttachVolume"]
            }
          }
        },
        {
          "name": "调度失败告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "reason": {
              "contains": ["FailedScheduling", "Insufficient"]
            }
          }
        },
        {
          "name": "资源压力告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "reason": {
              "contains": ["Pressure", "OutOf", "Evict"]
            }
          }
        },
        {
          "name": "僵尸进程告警",
          "enabled": true,
          "severity": "warning",
          "conditions": {
            "reason": {
              "contains": ["ProcessZ"]
            }
          }
        }
      ]
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedoor-info
  namespace: kubedoor
data:
  install-info.txt: |
    # ClickHouse
    ClickHouse WEBUI: http://{{ .Values.clickhouse.CK_HOST }}:{{ .Values.clickhouse.CK_HTTP_PORT }}/play
    ClickHouse 用户名: {{ .Values.clickhouse.CK_USER }}
    ClickHouse 密码: {{ .Values.clickhouse.CK_PASSWORD }}
    
    # TSDB
    {{- if eq .Values.tsdb.type "KubeDoor" }}
    时序数据库类型: KubeDoor (Victoria-Metrics-Single)
    Victoria-Metrics WEBUI: http://{{ .Values.tsdb.vm_single.user }}:{{ .Values.tsdb.vm_single.passwd }}@victoria-metrics.kubedoor:8428
    vmagent配置远程写地址: http://{{ .Values.tsdb.vm_single.user }}:{{ .Values.tsdb.vm_single.passwd }}@victoria-metrics.kubedoor:8428/api/v1/write
    注意: 跨K8S访问时，请把victoria-metrics.kubedoor:8428替换为您外部可访问的IP和端口
    {{- else if eq .Values.tsdb.type "Victoria-Metrics-Cluster" }}
    时序数据库类型: Victoria-Metrics-Cluster
    Victoria-Metrics远程读地址: http://{{ .Values.tsdb.remoteRead }}
    vmagent配置远程写地址: http://{{ .Values.tsdb.remoteWrite }}
    {{- else }}
    时序数据库类型: Victoria-Metrics-Single
    Victoria-Metrics WEBUI: {{ .Values.tsdb.url }}
    vmagent配置远程写地址: {{ .Values.tsdb.url }}/api/v1/write
    {{- end }}
    
    统一的external_labels_key: {{ .Values.tsdb.external_labels_key }}
    
    # KubeDoor web
    KubeDoor webUI: http://nodeIP:kubedoor-web nodeport
    默认账号密码都是: kubedoor

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoor-master
  namespace: kubedoor
  labels:
    app: kubedoor-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoor-master
  template:
    metadata:
      labels:
        app: kubedoor-master
    spec:
      containers:
        - name: kubedoor-master
          image: {{ .Values.image.repository }}/kubedoor-master:{{ .Values.image.kubedoor_master_tag }}
          envFrom:
            - configMapRef:
                name: kubedoor-config
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: kubedoor-master-file-cfg
              mountPath: /k8s_event/rules
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 1Mi
          livenessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: kubedoor-master-file-cfg
          configMap:
            name: kubedoor-master-file-cfg
            items:
              - key: alert_rules.json
                path: alert_rules.json

---

apiVersion: v1
kind: Service
metadata:
  name: kubedoor-master
  namespace: kubedoor
  labels:
    app: kubedoor-master
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: kubedoor-master
  type: ClusterIP 
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubedoor-collect
  namespace: kubedoor
spec:
  schedule: 0 1 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubedoor-collect
              image: registry.cn-shenzhen.aliyuncs.com/starsl/busybox-curl
              command:
                - /bin/sh
                - '-c'
                - curl -s 'http://kubedoor-master.kubedoor/api/cron_peak_data'
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
{{- end }}
